- hosts: localhost
  vars_files:
    - config.yml
  become: true
  pre_tasks:
    - name: Update Repositories
      apt: update_cache=yes
      changed_when: false
  tasks:
    - include: tasks/user.yml
    - include: tasks/zsh.yml
    - include: tasks/i3.yml
    - include: tasks/optional-software.yml
    - include: tasks/dotfiles.yml
    - include: tasks/system-cleanup.yml
