- name: Create the .config/kitty directory.
  file:
    path: "/home/{{ my_username }}/.config/kitty"
    state: directory
    mode: "0755"

- name: Placing Kitty CFG
  copy:
    src: files/dotfiles/kitty/kitty.conf
    dest: "/home/{{ my_username }}/.config/kitty/kitty.conf"
    owner: "{{ my_username }}"
    group: "{{ my_username }}"
    mode: 0700

- name: Placing Kitty Theme
  copy:
    src: files/dotfiles/kitty/snazzy.conf
    dest: "/home/{{ my_username }}/.config/kitty/snazzy.conf"
    owner: "{{ my_username }}"
    group: "{{ my_username }}"
    mode: 0700
