- name: Install Desktop I3 Packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - i3
      - xinit
      - dbus-x11
      - ubuntu-drivers-common
      - mesa-utils
      - mesa-utils-extra
      - gnupg
      - numlockx
      - xautolock
      - scrot
      - xorg
      - xserver-xorg
      - kitty
      - slick-greeter
      - lightdm
      - dconf-service
      - ssh-askpass
      - network-manager
      - vim-nox
      - lemonbar
      - xdg-utils
      - snapd-xdg-open

- name: Create the .config/i3 directory.
  file:
    path: "/home/{{ my_username }}/.config/i3"
    state: directory
    mode: "0755"

- name: Placing i3 CFG
  copy:
    src: files/dotfiles/i3/config
    dest: "/home/{{ my_username }}/.config/i3/config"
    owner: "{{ my_username }}"
    group: "{{ my_username }}"
    mode: "0664"

- name: Placing zprofile CFG
  copy:
    src: files/dotfiles/zsh/zprofile
    dest: "/home/{{ my_username }}/.zprofile"
    owner: "{{ my_username }}"
    group: "{{ my_username }}"
    mode: "0664"

- name: Download Meslo NerdFont for Powerline
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Meslo/S/Regular/complete/Meslo%20LG%20S%20Regular%20Nerd%20Font%20Complete.ttf
    dest: /usr/share/fonts/truetype/
    mode: "0644"
    owner: "root"
    group: "root"

- name: Download Meslo NerdFont Mono for Powerline
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Meslo/M/Regular/complete/Meslo%20LG%20M%20Regular%20Nerd%20Font%20Complete%20Mono.ttf
    dest: /usr/share/fonts/truetype/
    mode: "0644"
    owner: "root"
    group: "root"

- name: Downloading and Extract Font Awesome
  unarchive:
    src: https://use.fontawesome.com/releases/v{{font_awesome_version}}/fontawesome-free-{{font_awesome_version}}-desktop.zip
    dest: /tmp
    remote_src: yes

- name: Installing Font Awesome
  become: true
  copy:
    src: "{{ item }}"
    dest: /usr/share/fonts/opentype/
    mode: "0644"
    owner: "root"
    group: "root"
  with_fileglob:
    - /tmp/fontawesome-free-{{font_awesome_version}}-desktop/otfs/*

- name: Registering New Fonts
  become: true
  command: fc-cache -f -v

- name: Building slick-greeter.conf
  copy:
    src: files/dotfiles/slick-greeter/slick-greeter.conf
    dest: "/etc/lightdm/slick-greeter.conf"

- name: "Create wallpaper directory"
  file:
    path: /usr/share/wallpaper/
    state: directory
    mode: "0755"
    group: root
    owner: root

- name: Adding wallpaper
  copy:
    src: files/wallpaper/wallpaper.png
    dest: "/usr/share/wallpaper/wallpaper.png"
    mode: "0664"
    group: root
    owner: root
