- name: Install Desktop I3 Packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - i3
      - xinit
      - dbus-x11
      - ubuntu-drivers-common
      - mesa-utils
      - mesa-utils-extra
      - gnupg
      - numlockx
      - xautolock
      - scrot
      - xorg
      - xserver-xorg
      - xterm
      - slick-greeter
      - lightdm
      - dconf-service

- name: Placing xinitrc CFG
  copy:
    src: files/dotfiles/xinitrc
    dest: "/home/{{ my_username }}/.xinitrc"
    owner: "{{ my_username }}"
    group: "{{ my_username }}"
    mode: 0700

- name: Placing zprofile CFG
  copy:
    src: files/dotfiles/zprofile
    dest: "/home/{{ my_username }}/.zprofile"
    owner: "{{ my_username }}"
    group: "{{ my_username }}"
    mode: 0700

- name: Downloading and Extract Font Awesome
  unarchive:
    src: https://use.fontawesome.com/releases/v{{font_awesome_version}}/fontawesome-free-{{font_awesome_version}}-desktop.zip
    dest: /tmp
    remote_src: yes

- name: Installing Font Awesome
  become: true
  copy:
    src: "{{ item }}"
    dest: /usr/local/share/fonts/
  with_fileglob:
    - /tmp/fontawesome-free-{{font_awesome_version}}-desktop/otfs/*

- name: Registering New Fonts
  become: true
  command: fc-cache -f -v
