- name: Install Desktop I3 Packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - i3
      - ubuntu-drivers-common
      - mesa-utils
      - mesa-utils-extra
      - gnupg
      - numlockx
      - xautolock
      - scrot
      - xorg
      - xserver-xorg
- name: Autoremove and Purge APT Packages
  apt:
    autoremove: yes
    purge: yes
