- name: Install Desktop I3 Packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - i3
      - ubuntu-drivers-common
      - mesa-utils
      - mesa-utils-extra
      - gnupg
      - numlockx
      - xautolock
      - scrot
      - xorg
      - xserver-xorg

- name: Downloading and Extract Font Awesome
  unarchive:
    src: https://use.fontawesome.com/releases/v{{font_awesome_version}}/fontawesome-free-{{font_awesome_version}}desktop.zip
    dest: /tmp
    remote_src: yes
