- name: Install Desktop I3 Packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - wget
      - unzip
      - firefox
      - htop

- name: Enabling Snap Pacakge Support
  apt:
    name: snapd
